name: FIXXE
options:
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
targets:
  FIXXE:
    type: application
    platform: iOS
    sources:
      - FIXXE
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.karpinity.fixxe
        MARKETING_VERSION: "1.39"
        CURRENT_PROJECT_VERSION: "39"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: FIXXE
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
