// Автогенерировано из CurrencyViewModel.kt
const SYMBOLS = {"EUR": "€", "USD": "$", "GBP": "£", "JPY": "¥", "CHF": "Fr", "CAD": "C$", "AUD": "A$", "NZD": "NZ$", "CNY": "¥", "HKD": "HK$", "SGD": "S$", "RSD": "din.", "GEL": "₾", "ILS": "₪", "TJS": "SM", "RUB": "₽", "UAH": "₴", "TRY": "₺", "PLN": "zł", "CZK": "Kč", "HUF": "Ft", "RON": "lei", "SEK": "kr", "NOK": "kr", "DKK": "kr", "ISK": "kr", "MXN": "MX$", "BRL": "R$", "ARS": "AR$", "KRW": "₩", "THB": "฿", "IDR": "Rp", "MYR": "RM", "PHP": "₱", "VND": "₫", "INR": "₹", "PKR": "₨", "EGP": "E£", "ZAR": "R", "NGN": "₦", "SAR": "SR", "AED": "AED", "QAR": "QR", "KWD": "KD", "BHD": "BD", "OMR": "RO", "JOD": "JD", "AMD": "֏", "AZN": "₼", "KZT": "₸", "UZS": "soʻm", "MDL": "L", "BGN": "лв", "MKD": "ден", "ALL": "L", "BYN": "Br", "CLP": "CL$", "COP": "CO$", "PEN": "S/", "TWD": "NT$", "GHS": "GH₵", "MAD": "MAD", "DZD": "DA", "TND": "DT", "ETB": "Br", "TZS": "TSh", "KGS": "с"};
const NAMES = {"EUR": "Euro", "USD": "US Dollar", "GBP": "British Pound", "JPY": "Japanese Yen", "CHF": "Swiss Franc", "CAD": "Canadian Dollar", "AUD": "Australian Dollar", "NZD": "New Zealand Dollar", "CNY": "Chinese Yuan", "HKD": "Hong Kong Dollar", "SGD": "Singapore Dollar", "RSD": "Serbian Dinar", "GEL": "Georgian Lari", "ILS": "Israeli Shekel", "TJS": "Tajikistani Somoni", "RUB": "Russian Ruble", "UAH": "Ukrainian Hryvnia", "TRY": "Turkish Lira", "PLN": "Polish Zloty", "CZK": "Czech Koruna", "HUF": "Hungarian Forint", "RON": "Romanian Leu", "SEK": "Swedish Krona", "NOK": "Norwegian Krone", "DKK": "Danish Krone", "ISK": "Icelandic Krona", "MXN": "Mexican Peso", "BRL": "Brazilian Real", "ARS": "Argentine Peso", "KRW": "South Korean Won", "THB": "Thai Baht", "IDR": "Indonesian Rupiah", "MYR": "Malaysian Ringgit", "PHP": "Philippine Peso", "VND": "Vietnamese Dong", "INR": "Indian Rupee", "PKR": "Pakistani Rupee", "EGP": "Egyptian Pound", "ZAR": "South African Rand", "NGN": "Nigerian Naira", "SAR": "Saudi Riyal", "AED": "UAE Dirham", "QAR": "Qatari Riyal", "KWD": "Kuwaiti Dinar", "BHD": "Bahraini Dinar", "OMR": "Omani Rial", "JOD": "Jordanian Dinar", "AMD": "Armenian Dram", "AZN": "Azerbaijani Manat", "KZT": "Kazakhstani Tenge", "UZS": "Uzbekistani Som", "MDL": "Moldovan Leu", "BGN": "Bulgarian Lev", "MKD": "North Macedonian Denar", "ALL": "Albanian Lek", "BYN": "Belarusian Ruble", "CLP": "Chilean Peso", "COP": "Colombian Peso", "PEN": "Peruvian Sol", "TWD": "Taiwan Dollar", "GHS": "Ghanaian Cedi", "MAD": "Moroccan Dirham", "DZD": "Algerian Dinar", "TND": "Tunisian Dinar", "ETB": "Ethiopian Birr", "TZS": "Tanzanian Shilling", "KGS": "Kyrgyz Som", "AFN": "Afghan Afghani"};
const FLAGS = {"EUR": "🇪🇺", "USD": "🇺🇸", "GBP": "🇬🇧", "JPY": "🇯🇵", "CHF": "🇨🇭", "CAD": "🇨🇦", "AUD": "🇦🇺", "NZD": "🇳🇿", "CNY": "🇨🇳", "HKD": "🇭🇰", "SGD": "🇸🇬", "RSD": "🇷🇸", "GEL": "🇬🇪", "ILS": "🇮🇱", "TJS": "🇹🇯", "RUB": "🇷🇺", "UAH": "🇺🇦", "TRY": "🇹🇷", "PLN": "🇵🇱", "CZK": "🇨🇿", "HUF": "🇭🇺", "RON": "🇷🇴", "SEK": "🇸🇪", "NOK": "🇳🇴", "DKK": "🇩🇰", "ISK": "🇮🇸", "MXN": "🇲🇽", "BRL": "🇧🇷", "ARS": "🇦🇷", "KRW": "🇰🇷", "THB": "🇹🇭", "IDR": "🇮🇩", "MYR": "🇲🇾", "PHP": "🇵🇭", "VND": "🇻🇳", "INR": "🇮🇳", "PKR": "🇵🇰", "EGP": "🇪🇬", "ZAR": "🇿🇦", "NGN": "🇳🇬", "SAR": "🇸🇦", "AED": "🇦🇪", "QAR": "🇶🇦", "KWD": "🇰🇼", "BHD": "🇧🇭", "OMR": "🇴🇲", "JOD": "🇯🇴", "AMD": "🇦🇲", "AZN": "🇦🇿", "KZT": "🇰🇿", "UZS": "🇺🇿", "MDL": "🇲🇩", "BGN": "🇧🇬", "MKD": "🇲🇰", "ALL": "🇦🇱", "BYN": "🇧🇾", "CLP": "🇨🇱", "COP": "🇨🇴", "PEN": "🇵🇪", "TWD": "🇹🇼", "GHS": "🇬🇭", "MAD": "🇲🇦", "DZD": "🇩🇿", "TND": "🇹🇳", "ETB": "🇪🇹", "TZS": "🇹🇿", "KGS": "🇰🇬", "AFN": "🇦🇫"};
const DEFAULT_CURRENCIES = ["EUR","USD","RSD","GEL","ILS","TJS","CHF"];
const LANGUAGES = [
 ["en","English"],["sr","Srpski"],["hr","Hrvatski"],["bs","Bosanski"],["mk","Македонски"],
 ["sq","Shqip"],["sl","Slovenščina"],["bg","Български"],["el","Ελληνικά"],["ro","Română"],
 ["de","Deutsch"],["fr","Français"],["es","Español"],["it","Italiano"],["pt","Português"],
 ["nl","Nederlands"],["pl","Polski"],["cs","Čeština"],["sk","Slovenčina"],["hu","Magyar"],
 ["sv","Svenska"],["da","Dansk"],["nb","Norsk"],["fi","Suomi"],["lt","Lietuvių"],
 ["lv","Latviešu"],["et","Eesti"],["ru","Русский"],["ka","ქართული"],["zh","中文"],
 ["ja","日本語"],["ko","한국어"],["th","ไทย"],["vi","Tiếng Việt"],["id","Bahasa Indonesia"],
 ["hi","हिन्दी"],["ar","العربية"],["he","עברית"],["fa","فارسی"],["tr","Türkçe"]
];
const RTL_LANGS = ["ar","he","fa"];
